//! Build-time asset embedder: walks art/, sounds/packs and assets/fonts and writes
//! `<out>/assets.zig` (a sorted path index) + `<out>/blob.bin` (the file bytes), so the
//! app binary carries exactly the SVG / JSON / WAV / TTF files it needs at runtime.
//!
//! usage: gen_assets <repo root> <out dir>

const std = @import("std");
const Io = std.Io;
const Allocator = std.mem.Allocator;

const File = struct { path: []const u8, data: []const u8 };

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 3) return error.Usage;
    var root = try Io.Dir.cwd().openDir(io, args[1], .{});
    defer root.close(io);
    var files: std.ArrayList(File) = .empty;

    try addArt(arena, io, root, &files);
    try addSounds(arena, io, root, &files);
    try addDir(arena, io, root, "assets/fonts", &files, &.{ ".ttf", ".txt" });

    std.mem.sort(File, files.items, {}, struct {
        fn lt(_: void, a: File, b: File) bool {
            return std.mem.lessThan(u8, a.path, b.path);
        }
    }.lt);

    var out = try Io.Dir.cwd().createDirPathOpen(io, args[2], .{});
    defer out.close(io);
    var blob: std.ArrayList(u8) = .empty;
    var src: std.ArrayList(u8) = .empty;
    try src.appendSlice(arena,
        \\//! Generated by tools/gen_assets.zig: every runtime asset, embedded.
        \\pub const Entry = struct { path: []const u8, off: u32, len: u32 };
        \\pub const blob = @embedFile("blob.bin");
        \\pub const entries = [_]Entry{
        \\
    );
    for (files.items) |f| {
        // 4-byte alignment keeps WAV sample data aligned enough for i16 reads.
        while (blob.items.len % 4 != 0) try blob.append(arena, 0);
        try src.print(arena, "    .{{ .path = \"{s}\", .off = {d}, .len = {d} }},\n", .{ f.path, blob.items.len, f.data.len });
        try blob.appendSlice(arena, f.data);
    }
    try src.appendSlice(arena, "};\n");
    try out.writeFile(io, .{ .sub_path = "blob.bin", .data = blob.items });
    try out.writeFile(io, .{ .sub_path = "assets.zig", .data = src.items });
}

fn hasSuffix(name: []const u8, exts: []const []const u8) bool {
    for (exts) |e| if (std.mem.endsWith(u8, name, e)) return true;
    return false;
}

fn read(arena: Allocator, io: Io, root: Io.Dir, path: []const u8) ![]const u8 {
    return root.readFileAlloc(io, path, arena, .limited(64 << 20));
}

/// art/<dir>/*.svg|json and art/<dir>/acc/*.svg; skips _src/, preview/, reference_* and notes.
fn addArt(arena: Allocator, io: Io, root: Io.Dir, files: *std.ArrayList(File)) !void {
    var art = try root.openDir(io, "art", .{ .iterate = true });
    defer art.close(io);
    var it = art.iterate();
    while (try it.next(io)) |e| {
        if (e.kind != .directory) continue;
        const base = try std.fmt.allocPrint(arena, "art/{s}", .{e.name});
        try addDir(arena, io, root, base, files, &.{ ".svg", ".json" });
        const acc = try std.fmt.allocPrint(arena, "{s}/acc", .{base});
        addDir(arena, io, root, acc, files, &.{".svg"}) catch |err| switch (err) {
            error.FileNotFound => {},
            else => return err,
        };
    }
}

fn addDir(arena: Allocator, io: Io, root: Io.Dir, sub: []const u8, files: *std.ArrayList(File), exts: []const []const u8) !void {
    var d = try root.openDir(io, sub, .{ .iterate = true });
    defer d.close(io);
    var it = d.iterate();
    while (try it.next(io)) |e| {
        if (e.kind != .file and e.kind != .sym_link) continue;
        if (!hasSuffix(e.name, exts)) continue;
        if (std.mem.startsWith(u8, e.name, "reference_")) continue;
        const path = try std.fmt.allocPrint(arena, "{s}/{s}", .{ sub, e.name });
        try files.append(arena, .{ .path = path, .data = try read(arena, io, root, path) });
    }
}

/// sounds/packs/index.json + every pack it marks `bundle: "default"` whose license is not GPL.
fn addSounds(arena: Allocator, io: Io, root: Io.Dir, files: *std.ArrayList(File)) !void {
    const index_path = "sounds/packs/index.json";
    const index = try read(arena, io, root, index_path);
    const Index = struct { packs: []const struct { id: []const u8, bundle: []const u8 = "" } };
    const parsed = try std.json.parseFromSliceLeaky(Index, arena, index, .{ .ignore_unknown_fields = true });
    var kept: std.ArrayList(u8) = .empty;
    try kept.appendSlice(arena, "{\"format\":\"typebud.soundpack-index\",\"format_version\":1,\"packs\":[");
    var n: usize = 0;
    for (parsed.packs) |p| {
        if (!std.mem.eql(u8, p.bundle, "default")) continue;
        const dir = try std.fmt.allocPrint(arena, "sounds/packs/{s}", .{p.id});
        const pj_path = try std.fmt.allocPrint(arena, "{s}/pack.json", .{dir});
        const pj = try read(arena, io, root, pj_path);
        const License = struct { license: []const u8 = "" };
        const lic = try std.json.parseFromSliceLeaky(License, arena, pj, .{ .ignore_unknown_fields = true });
        if (std.mem.startsWith(u8, lic.license, "GPL")) continue;
        try files.append(arena, .{ .path = pj_path, .data = pj });
        const license_path = try std.fmt.allocPrint(arena, "{s}/LICENSE", .{dir});
        if (read(arena, io, root, license_path)) |l| try files.append(arena, .{ .path = license_path, .data = l }) else |_| {}
        for ([_][]const u8{ "down", "up" }) |sub| {
            const sd = try std.fmt.allocPrint(arena, "{s}/{s}", .{ dir, sub });
            addDir(arena, io, root, sd, files, &.{".wav"}) catch |err| switch (err) {
                error.FileNotFound => {},
                else => return err,
            };
        }
        if (n > 0) try kept.append(arena, ',');
        try kept.print(arena, "{{\"id\":\"{s}\",\"bundle\":\"default\"}}", .{p.id});
        n += 1;
    }
    try kept.appendSlice(arena, "]}");
    try files.append(arena, .{ .path = index_path, .data = kept.items });
}
